### ISSUE TITLE
For US and CA, old instances are not terminated after new instances deployed.

### ISSUE THREAD

**Issue by roy-gunter** [angelamancini/deployer#75]
I only waited an hour, but the old instances were not terminated.  Old View instances were terminated about 3 minutes after new instances were complete.

**Comment by angelamancini** [comment]
I've seen this caused by machines failing to boot due to missing inputs on the RightScale array. Not sure if this is the same issue.

**Comment by angelamancini** [comment]
I have yet to see this in action. Will reopen if it crops up again.
