### ISSUE TITLE
make tagging smarter, but only a little

### ISSUE THREAD

**Issue by erumble** [angelamancini/deployer#76]
The tagging code should increment the numeric portion of the tag, and then append the appropriate branch identifier. Not use the last tag's branch identifier.  

It should follow the rules listed below:
* tagging master, append `-m`
* tagging release, append `-r`
* tagging production, append `-p`
* tagging development, append `-d`
* tagging any other branch, append `-f`

**Bonus**: when tagging with `-f`, include the branch name in the release notes

This should resolve issue #40 and issue #74

**Comment by angelamancini** [comment]
looks good to me
