### ISSUE TITLE
Show error message on strand

### ISSUE THREAD

**Issue by angelamancini** [angelamancini/deployer#81]
When a server strands, we need to see the audit entry of the stranded server showing the error.

If it is a code issue, we should allow the server to be deployed with a different tag (or re-tagged)
If it is a server/script/rightscale issue, we should not allow the user to deploy again until it is fixed.

**Comment by Sjeanpierre** [comment]
![deploying_strandy](https://cloud.githubusercontent.com/assets/673382/7305614/347548b6-e9cd-11e4-9bbf-f88b168daf1e.jpg)
Show status in red not green

**Comment by angelamancini** [comment]
Deployinator now shows the error messages when a server strands.
